<?php
/**
 * Created by PhpStorm.
 * User: zhongyongbiao
 * Date: 2018/10/26
 * Time: 下午4:21
 */

namespace App\Utility;


use EasySwoole\Config;
use EasySwoole\Core\Component\Pool\AbstractInterface\Pool;
use EasySwoole\Core\Component\Trigger;
use EasySwoole\Core\Swoole\Coroutine\Client\Mysql;

class MysqlPool extends Pool
{
    public function getObj($timeOut = 0.1)
    {
        // TODO: Change the autogenerated stub
        return parent::getObj($timeOut);
    }

    protected function createObject()
    {
        // TODO: Implement createObject() method.
        try {
            $conf = Config::getInstance()->getConf('mysql');
            $db = new Mysql([
                'db' => $conf['db'],
                'host' => $conf['host'],
                'port' => $conf['port'],
                'username' => $conf['user'],
                'password' => $conf['password']
            ]);
            if (isset($conf['names'])) {
                $db->rawQuery('SET NAMES ' . $conf['names']);
            }
            return $db;
        } catch (\Throwable $throwable) {
            Trigger::throwable($throwable);
            return null;
        }
    }

}