<?php
/**
 * Created by PhpStorm.
 * User: zhongyongbiao
 * Date: 2018/10/26
 * Time: 下午4:59
 */

namespace App\Utility;


use EasySwoole\Config;
use EasySwoole\Core\Component\Pool\AbstractInterface\Pool;

class RedisPool extends Pool
{
    public function getObj($timeOut = 0.1)
    {
        // TODO: Change the autogenerated stub
        return parent::getObj($timeOut);
    }

    protected function createObject()
    {
        // TODO: Implement createObject() method.
        $conf = Config::getInstance()->getConf('redis');
        $redis = new \EasySwoole\Core\Swoole\Coroutine\Client\Redis($conf['host'], $conf['port'], $conf['serialize'], $conf['auth']);
        if (is_callable($conf['errorHandler'])) {
            $redis->setErrorHandler($conf['errorHandler']);
        }
        try {
            $redis->exec('select', $conf['db_name']);
        } catch (\Throwable $throwable) {
            Logger::getInstance()->log($throwable->__toString() . "\n", 'exception');
            return null;
        }
        return $redis;
    }
}